quarkus:
  datasource:
    db-kind: postgresql
    username: postgres
    password: postgres
    jdbc:
      url: jdbc:postgresql://localhost:5432/postgres
  hibernate-orm:
    database:
      generation: validate
  flyway:
    migrate-at-start: true
    locations: db/migration
  swagger-ui:
    always-include: true
    path: /swagger
