name: Auto Bump Version

on:
  pull_request:
    branches:
      - main

jobs:
  auto-bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Extract PR version
        id: pr
        run: |
          pr_version=$(grep -m 1 '<version>' pom.xml | sed -E 's/.*<version>([^<]+)<\/version>.*/\1/')
          echo "version=$pr_version" >> "$GITHUB_OUTPUT"

      - name: Get main version
        run: |
          git fetch origin main --depth=1
          main_version=$(git show origin/main:pom.xml | grep -m 1 '<version>' | sed -E 's/.*<version>([^<]+)<\\/version>.*/\1/')
          echo "MAIN_VERSION=$main_version" >> $GITHUB_ENV

      - name: Bump patch version if equal
        if: steps.pr.outputs.version == env.MAIN_VERSION
        run: |
          new_version=$(python -c "
          import os,re,sys; 
          v=os.environ['VERSION']; 
          m=re.match(r'(\\d+)\\.(\\d+)\\.(\\d+)(.*)', v); 
          sys.exit('Invalid version') if not m else None; 
          maj, mi, pa, suf = m.groups(); 
          print(f'{maj}.{mi}.{int(pa)+1}{suf}')
          ")
          ./mvnw -q versions:set -DnewVersion="$new_version" -DgenerateBackupPoms=false
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git commit -am "chore: bump version to $new_version"
          git push
        env:
          VERSION: ${{ steps.pr.outputs.version }}
