name: Validate PR Version and Bump if Equal

on:
  pull_request:
    branches:
      - main

jobs:
  validate-and-bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Fetch main branch
        run: git fetch origin main

      - name: Get versions
        run: |
          MAIN_VERSION=$(git show origin/main:pom.xml | grep -m1 -oP '(?<=<version>)[^<]+')
          PR_VERSION=$(grep -m1 -oP '(?<=<version>)[^<]+' pom.xml)
          
          echo "MAIN_VERSION=$MAIN_VERSION" >> $GITHUB_ENV
          echo "PR_VERSION=$PR_VERSION" >> $GITHUB_ENV
          echo "Main: $MAIN_VERSION, PR: $PR_VERSION"

      - name: Decide and act
        run: |
          MAIN=$(echo "$MAIN_VERSION" | sed 's/-SNAPSHOT//')
          CURRENT=$(echo "$PR_VERSION" | sed 's/-SNAPSHOT//')
          
          if dpkg --compare-versions "$CURRENT" "lt" "$MAIN"; then
            echo "::error::PR version $PR_VERSION is less than main $MAIN_VERSION"
            exit 1
          
          elif dpkg --compare-versions "$CURRENT" "eq" "$MAIN"; then
            echo "PR version equals main. Bumping..."
          
            IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT"
            NEW_PATCH=$((PATCH + 1))
            NEW_VERSION="${MAJOR}.${MINOR}.${NEW_PATCH}-SNAPSHOT"
          
            sed -i '0,/<version>[^<]*<\/version>/{s#<version>[^<]*</version>#<version>'"$NEW_VERSION"'</version>#}' pom.xml
          
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
          
            git commit -am "chore: bump version to $NEW_VERSION"
            
          
            echo "::error::Version was equal. Bumped to $NEW_VERSION. Please re-run checks on new commit."
            exit 1 && git push origin HEAD:${{ github.head_ref }}
          
          else
            echo "PR version $PR_VERSION is greater than main $MAIN_VERSION. All good."
          fi
