name: Validate PR Version and Bump if Equal

on:
  pull_request:
    branches:
      - main

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Fetch main branch
        run: git fetch origin main

      - name: Get versions
        run: |
          MAIN_VERSION=$(git show origin/main:pom.xml | grep -m1 -oP '(?<=<version>)[^<]+')
          PR_VERSION=$(grep -m1 -oP '(?<=<version>)[^<]+' pom.xml)
          
          echo "MAIN_VERSION=$MAIN_VERSION" >> $GITHUB_ENV
          echo "PR_VERSION=$PR_VERSION" >> $GITHUB_ENV
          echo "Main: $MAIN_VERSION, PR: $PR_VERSION"

      - name: Validate version
        run: |
          MAIN=$(echo "$MAIN_VERSION" | sed 's/-SNAPSHOT//')
          CURRENT=$(echo "$PR_VERSION" | sed 's/-SNAPSHOT//')
          
          if dpkg --compare-versions "$CURRENT" "le" "$MAIN"; then
            echo "::error::PR version $PR_VERSION is not greater than main $MAIN_VERSION"
            exit 1
          else
            echo "PR version $PR_VERSION is greater than main $MAIN_VERSION. All good."
          fi
